# Generated by Django 4.0.5 on 2022-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('laboratory', '研究室'), ('procurement', '購買'), ('cafeteria', '食堂'), ('other_on_campus', 'その他学内'), ('returning_home', '帰宅'), ('off_campus', 'その他学外')], max_length=20)),
            ],
        ),
    ]
